[package]
name = "ipfs-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libipld = "0.16.0"
ipfs-embed = "0.26.0"
